# Production inventory
# This file is overwritten dynamically in GitHub Actions workflow
# with actual values from GitHub Secrets

[production]
production_server ansible_host=<SSH_HOST> ansible_user=<SSH_USER> ansible_port=<SSH_PORT> ansible_ssh_private_key_file=/tmp/ssh_key
